apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rhfp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-rhfp@sha256:4f75b01436bfa1dc66d2143cbc56d7c765680cda491190f9f4604a1fd5609b1a
        name: my-nodejs
        resources: {}
status: {}
